config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('src.page.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('src.user.urls')),
    path('post/', include('src.post.urls.post')),
    path('feeling/', include('src.post.urls.feeling')),
    path('comment/', include('src.post.urls.comment')),
    path('chat/', include('src.chat.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/chat/urls.py
from django.urls import path

from . import views
from ..page.views import chat_page_view

app_name = 'chat'

urlpatterns = [
    path('', chat_page_view, name='chat_page'),
    path('history/<str:room_id>/', views.history, name='history'),
    path('unauthorized/', views.unauthorized, name='unauthorized'),
    path('<str:group_id>/', views.room, name='room'),
]

src/page/urls.py
from django.urls import path

from src.page.views import homepage_view, profile_page_view, privacy_setting_page_view
from src.user.views import profile_update_view

app_name = 'page'

urlpatterns = [
    path('', homepage_view, name='homepage'),
    path('profile/<str:username>/', profile_page_view, name='profile_page'),
    path('profile_update/', profile_update_view, name='profile_update'),
    path('privacy_setting/', privacy_setting_page_view, name='privacy_setting_page'),
]

src/user/urls.py
from django.urls import path

from src.user.views import friend_request_comfirm, friend_request_delete, profile_update

app_name = 'user'

urlpatterns = [
    path('friend/comfirm/<int:friend_request_id>/', friend_request_comfirm, name='friend_request_confirm'),
    path('friend/delete/<int:friend_request_id>/', friend_request_delete, name='friend_request_delete'),
    path('profile_update/process/', profile_update, name='profile_update_process'),
]

templates/components/_header.html
{% load static %}
<header class="header">
    <!-- ----------------------------- Top Navbar ------------------------------ -->
    <nav class="navbar">
        <div class="navbar__brand">
            <a class="navbar__logo" href="#">
                <img src="{% static 'images/logo.png' %}" alt="" class="d-inline-block align-text-top">
                <span>ORY</span>
            </a>
            <div class="navbar__toggle">
                <i class='bx bx-menu'></i>
            </div>
        </div>
        <div class="navbar__searchbar">
            <form class="search-form">
                <input class="form-control" type="text" placeholder="Search">
                <button class="btn" type="submit">
                    <i class='bx bx-search'></i>
                </button>
            </form>
        </div>
        <div class="navbar__menu">
            <a href="{% url 'page:profile_page' request.user.username %}" class="user-link">
                <img src="{{ request.user.get_avatar }}" alt="user">
                <span>{{ request.user.username }}</span>
            </a>
            <a href="{% url 'page:homepage' %}">
                <i class='bx bxs-home'></i>
            </a>
            <div class="btn-group">
                <button class="btn" type="button" id="messageUserId" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <i class='bx bxs-group'></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="messageUserId">
                    {% with user.get_friend_request|slice:":5" as friends_request_of_user %}
                        <div class="bg-primary p-3">
                            <h4 class="mb-0 text-white">Friend Request<small
                                    class="badge badge-light float-right">{{ friends_request_of_user.count }}</small>
                            </h4>
                        </div>
                        {% for friend_request in friends_request_of_user %}
                            <a class="dropdown-item">
                                <div class="icon">
                                    <img class="img-45 radius-50" src="{{ friend_request.inviter.get_avatar }}"
                                         alt="user-img">
                                </div>
                                <div class="description">
                                    <h5 class="">{{ friend_request.inviter.username }}</h5>
                                    <small class="">{{ friend_request.sent_at|timesince }}</small>
                                    <p>{{ friend_request.inviter.get_friend_quantity }} friends</p>
                                </div>
                                <button class="btn btn-primary">Confirm</button>
                                <button class="btn btn-danger">Delete Request</button>
                            </a>


                            {% comment %}<div class="iq-friend-request">
                                <div class="iq-sub-card iq-sub-card-big d-flex align-items-center justify-content-between">
                                    <div class="d-flex align-items-center">
                                        <div class="">
                                            <img class="avatar-40 rounded-circle"
                                                 src="{{ friend_request.inviter.get_avatar }}"
                                                 alt="">
                                        </div>
                                        <div class="media-body ml-3">
                                            <h6 class="mb-0 ">{{ friend_request.inviter.username }}</h6>
                                            <p class="mb-0">{{ friend_request.inviter.get_friend_quantity }} friends</p>
                                        </div>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <a hx-post="{% url 'user:friend_request_comfirm' friend_request.id %}"
                                           hx-target="#friend-request-popup" hx-swap="outerHTML"
                                           class="mr-3 btn btn-primary rounded">Confirm</a>
                                        <a hx-post="{% url 'user:friend_request_delete' friend_request.id %}"
                                           hx-target="#friend-request-popup" hx-swap="outerHTML"
                                           class="mr-3 btn btn-secondary rounded">Delete Request</a>
                                    </div>
                                </div>
                            </div>{% endcomment %}

                        {% empty %}
                            <div class="d-flex justify-content-center">
                                <p>You don't have friend request.</p>
                            </div>
                        {% endfor %}
                        <div class="text-center">
                            <a href="#" class="mr-3 btn text-primary">View More Request</a>
                        </div>
                    {% endwith %}
                </div>
            </div>
            <div class="btn-group">
                <button class="btn" type="button" id="messageUserId" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <i class='bx bxs-message'></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="messageUserId">
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>Hello</p>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>Hello</p>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>Hello</p>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>Hello</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="btn-group">
                <button class="btn" type="button" id="notificationUserId" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <i class='bx bxs-bell'></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationUserId">
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>has add a story</p>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>has add a story</p>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>has add a story</p>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="icon">
                            <img class="img-45 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-avatar">
                        </div>
                        <div class="description">
                            <h5 class="">Bni Emma Watson</h5>
                            <small class="">13 Mar</small>
                            <p>has add a story</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="btn-group">
                <button class="btn" type="button" id="userMenu" data-bs-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                    <i class='bx bxs-down-arrow'></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="userMenu">
                    <a href="{% url 'page:profile_page' request.user.username %}" class="dropdown-item">
                        <div class="icon">
                            <i class='bx bxs-user-account'></i>
                        </div>
                        <div class="description">
                            <h5 class="">My Profile</h5>
                            <p class="">View personal profile details.</p>
                        </div>
                    </a>
                    <a href="{% url 'page:profile_page' request.user.username %}" class="dropdown-item">
                        <div class="icon">
                            <i class='bx bx-edit'></i>
                        </div>
                        <div class="description">
                            <h5 class="">Edit Profile</h5>
                            <p class="">Edit your personal details.</p>
                        </div>
                    </a>
                    <a href="{% url 'page:profile_page' request.user.username %}" class="dropdown-item">
                        <div class="icon">
                            <i class='bx bx-user-pin'></i>
                        </div>
                        <div class="description">
                            <h5 class="">Account Settings</h5>
                            <p class="">Manager your account parameters.</p>
                        </div>
                    </a>
                    <a href="{% url 'page:profile_page' request.user.username %}" class="dropdown-item">
                        <div class="icon">
                            <i class='bx bx-lock'></i>
                        </div>
                        <div class="description">
                            <h5 class="">Privacy Settings</h5>
                            <p class="">Control your privacy parameters.</p>
                        </div>
                    </a>
                    <a href="{% url 'page:profile_page' request.user.username %}" class="dropdown-item">
                        <div class="icon">
                            <i class='bx bx-exit'></i>
                        </div>
                        <div class="description">
                            <h5 class="">Logout Account</h5>
                            <p class="">Logout your account soon.</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </nav>
</header>

templates/components/_list_post.html
<div class="post-list">
    {% for post in post_list %}
        <div class="part post">
            <div class="post__user-data">
                <div class="user-img">
                    <img class="img-60 radius-50" src="{{ post.user.get_avatar }}" alt="avatar">
                </div>
                <div class="info">
                    <h4 class="">
                        <a href="{% url 'page:profile_page' post.user.username %}" class="">{{ post.user.username }}</a>
                    </h4>
                    <p class="">{{ post.created_at|timesince }}</p>
                </div>
                <div class="btn-group post-toolbar">
                    <button class="btn" type="button" id="postToolbarId" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        <i class='bx bx-dots-vertical-rounded'></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="postToolbarId">
                        <a class="dropdown-item" href="#">
                            <div class="icon">
                                <i class='bx bx-save'></i>
                            </div>
                            <div class="description">
                                <h5>Save Post</h5>
                                <p class="">Add this to your saved items</p>
                            </div>
                        </a>
                        <a class="dropdown-item" href="#">
                            <div class="icon">
                                <i class='bx bx-window-close'></i>
                            </div>
                            <div class="description">
                                <h5>Hide Post</h5>
                                <p class="">See fewer posts like this.</p>
                            </div>
                        </a>
                        <a class="dropdown-item" href="#">
                            <div class="icon">
                                <i class='bx bx-user-x'></i>
                            </div>
                            <div class="description">
                                <h5>Unfollow User</h5>
                                <p class="">Stop seeing posts but stay friends.</p>
                            </div>
                        </a>
                        <a class="dropdown-item" href="#">
                            <div class="icon">
                                <i class='bx bx-bell'></i>
                            </div>
                            <div class="description">
                                <h5>Notifications</h5>
                                <p class="">Turn on notifications for this post</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="post__content">
                <p>{{ post.content }}</p>
            </div>
            <div class="post__media">
                <div class="d-flex flex-wrap">
                    {% if post.images_of_post %}
                        {% for image in post.images_of_post.all %}
                            <div class="col-md-6">
                                <a href="#">
                                    <img src="{{ image.media.url }}" alt="post-image"
                                         class="rounded">
                                </a>
                            </div>
                        {% endfor %}

                    {% endif %}

                </div>
            </div>
            <div class="post__comment">
                {% with post.comments_on_post.all as comments_on_post %}
                    <div class="comment__top">
                        <div class="like-block">
                            <a class="like-link" href="{% url 'feeling:express_feeling' post.id %}" data-post="{{ post.id }}">
                                {# Check whether user is expressed emotion on the post#}
                                {% if request.user in post.get_expressed_users %}
                                    <i class='bx bxs-heart'></i>
                                {% else %}
                                    <i class="bx bx-heart"></i>
                                {% endif %}
                            </a>
                            {% with post.expressed_users.all as expressed_users %}
                                <span>{{ expressed_users.count }} Likes</span>
                            {% endwith %}

                            <span>{{ comments_on_post.count }} Comments</span>
                        </div>
                        <div class="share-block">
                            <a href="">
                                <i class='bx bx-share'></i>
                                <span class="">99 Share</span>
                            </a>
                        </div>
                    </div>
                    <hr>
                    <ul class="comment__list list-comment-{{ post.id }}">
                        {% for comment in comments_on_post %}

                            <li class="comment">
                                <div class="user-img">
                                    <img src="{{ comment.user.get_avatar }}" alt="userimg" class="img-45 radius-50">
                                </div>
                                <div class="comment__data">
                                    <h5>{{ comment.user.username }}</h5>
                                    <p class="">{{ comment.content }}</p>
                                    <div class="comment-activity">
                                        <a href="">like</a>
                                        <a href="">reply</a>
                                        <span> {{ comment.created_at|timesince }} </span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% endwith %}

                <form class="comment__form comment-form-{{ post.id }}">
                    <input type="text" class="form-control" name="content" placeholder="Type comment here...">
                    <div class="comment-attagement">
                        <a href="">
                            <i class='bx bx-link'></i>
                        </a>
                        <a href="">
                            <i class='bx bx-smile'></i></i>
                        </a>
                        <a href="">
                            <i class='bx bx-camera'></i></i>
                        </a>
                    </div>
                    <button type="submit" class="btn submit-add-comment" data-post="{{ post.id }}">
                        <i class='bx bx-send'></i>
                    </button>
                </form>
            </div>
        </div>
    {% endfor %}
</div>

templates/components/_right_sidebar.html
{% load static %}
<div class="right-sidebar">

    <div class="right-sidebar__item">
        <div class="user-img status-online">
            <img class="img-50 radius-50" src="{% static 'images/user-1.jpg' %}" alt="user-img">
        </div>
        <div class="description">
            <h4 class=""><a href="#">Anna Sthesia</a></h4>
            <span class="">Just Now</span>
        </div>
    </div>
    <div class="right-sidebar__item">
        <div class="user-img status-online">
            <img class="img-50 radius-50" src="{% static 'images/user-2.jpg' %}" alt="user-img">
        </div>
        <div class="description">
            <h4 class=""><a href="#">Anna Sthesia</a></h4>
            <span class="">Just Now</span>
        </div>
    </div>
    <div class="right-sidebar__item">
        <div class="user-img status-online">
            <img class="img-50 radius-50" src="{% static 'images/user-3.jpg' %}" alt="user-img">
        </div>
        <div class=" description">
            <h4 class=""><a href="#">Anna Sthesia</a></h4>
            <span class="">Just Now</s>
        </div>
    </div>
</div>

templates/components/_sidebar.html
<div class="sidebar">
    <nav class="sidebar__menu">
        <ul class="menu">
            <li class="active" class="menu__item">
                <a href="{% url 'page:homepage' %}" class="">
                    <i class='bx bx-news'></i>
                    <span>Newsfeed</span></a>
            </li>
            <li class="active" class="menu__item">
                <a href="#" class="">
                    <i class='bx bx-group'></i>
                    <span>Group</span></a>
            </li>
            <li class="active" class="menu__item">
                <a href="{% url 'chat:chat_page' %}" class="">
                    <i class='bx bx-conversation'></i>
                    <span>Chat</span></a>
            </li>
            <li class="active" class="menu__item">
                <a href="#" class="">
                    <i class='bx bx-calendar-event'></i>
                    <span>Event</span></a>
            </li>
        </ul>
    </nav>
</div>